# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

  # seeder:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.seeder
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgresql+psycopg2://user:password@db:5432/test_db

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    #volumes:
    # - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/test_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  db_data:
