name = "backend"
compatibility_date = "2024-08-09"

# [vars]
# DB_NAME = "seen-culture-app"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "OBJECT_STORAGE"
bucket_name = "photo-sharing"

[[d1_databases]]
binding = "DB"
database_name = "photo-app-db"
database_id = "278c6490-5e7b-41bd-9b70-3a2ba2b51d4c"

# [ai]
# binding = "AI"