name = "backend"
compatibility_date = "2024-08-06"

[vars]
R2_ACCESS_KEY_ID = "59453ee0ed2bfd595587930dd7e9947f"
R2_SECRET_ACCESS_KEY = "504771ea7971fde7ff24534f12068900fe308cf1832e267b742f8d6e92468138"
BUCKET_NAME = "photo-app-bucket"
ACCOUNT_ID = "ac194df9613976b4e3cfb4ca4b9fd173"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "OBJECT_STORAGE"
bucket_name = "photo-app-bucket"
preview_bucket_name = "photo-app-bucket"

[[d1_databases]]
binding = "DB"
database_name = "photo-app-db"
database_id = "2f452882-7dc7-4505-8099-87346ddc0182"

# [ai]
# binding = "AI"